enemy =self.findNearestEnemy()
self.attack(enemy)
self.attack(enemy)
enemy =self.findNearestEnemy()
self.attack(enemy)
self.attack(enemy)
enemy =self.findNearestEnemy()
self.attack(enemy)
self.attack(enemy)